# Лабораторная работа №3
## Выполнил студент группы БВТ2005 Голубков Антон

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
4. [Вывод](#Вывод)

> Дополнительные модули, использованные при выполнение лабораторной

In [8]:
# Необходим при замере скорости выполнения кода
from datetime import datetime as t
# Нужен для создания словаря в алг. Бойера-Мура
from collections import defaultdict

### Задание №1
Реализовать методы поиска подстроки в строке. Добавить возможность ввода строки и подстроки с клавиатуры. Предусмотреть возможность существования пробела. Реализовать возможность выбора опции чувствительности или нечувствительности к регистру. Оценить время работы каждого алгоритма поиска и сравнить его со временем работы стандартной функции поиска, используемой в выбранном языке программирования.

#### Алгоритм Кнута-Морриса-Пратта

In [9]:
def prefix(pattern):
    pi = [0 for i in range(len(pattern))]
    j = 0
    i = 1
    while i < len(pi):
        if pattern[j] == pattern[i]:
            pi[i] = j + 1
            i += 1
            j += 1
        elif j == 0:
            pi[i] = 0
            i += 1
        else:
            j = pi[j - 1]
    return pi

def kmp(string, pattern, case_flag):
    if case_flag:
        string = string.lower()
        pattern = pattern.lower()
    matches = []
    pi = prefix(pattern)
    i = 0
    j = 0
    while i < len(string):
        if string[i] == pattern[j]:
            i += 1
            j += 1 
            if j == len(pattern):
                matches.append(i - j)
                j = pi[j - 1]
        else:
            if j > 0:
                j = pi[j - 1]
            else:
                i += 1
    return matches

print("string: ", end = '')
string = input()
print("pattern: ", end = '')
pattern = input()
print(f"prefix table: {prefix(pattern)}")
t1 = t.now()
result = kmp(string, pattern, True)
t2 = t.now() - t1
print(f"matches: {result}")
print(f"time: {t2}")

string: oniOnions plonionso
pattern: onions
prefix table: [0, 0, 0, 1, 2, 0]
matches: [3, 12]
time: 0:00:00.001000


#### Упрощенный алгоритм Бойера-Мура

In [10]:
def shift(pattern):
    table = defaultdict(lambda: len(pattern))
    for i in range(len(pattern) - 1):
        table[pattern[i]] = len(pattern) - 1 - i
    return table

def bmh(string, pattern, case_flag):
    if case_flag:
        string = string.lower()
        pattern = pattern.lower()
    matches = []
    table = shift(pattern)
    i = len(pattern) - 1
    while i < len(string):
        k = 0
        while k < len(pattern) and string[i - k] == pattern[len(pattern) - 1 - k]:
            k += 1
        if k != len(pattern):
            i += table[string[i]]
        else:
            matches.append(i - len(pattern) + 1)
            i += table[string[i]]
    return matches

print("string: ", end = '')
string = input()
print("pattern: ", end = '')
pattern = input()
t1 = t.now()
result = bmh(string, pattern, True)
t2 = t.now() - t1
print(f"matches: {result}")
print(f"time: {t2}")

string: oniOnions plonionso
pattern: onions
matches: [3, 12]
time: 0:00:00


### Задание №2
Написать программу, определяющую, является ли данное
расположение «решаемым», то есть можно ли из него за конечное число
шагов перейти к правильному. Если это возможно, то необходимо найти хотя
бы одно решение - последовательность движений, после которой числа будут
расположены в правильном порядке.
#### Входные данные: массив чисел, представляющий собой расстановку в
Порядке «слева направо, сверху вниз». Число 0 обозначает пустое поле.
Например, массив [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0] представляет
собой «решенную» позицию элементов.
#### Выходные данные: если решения нет, то функция должна вернуть
Пустой массив []. Если решение есть, то необходимо представить решение —
для каждого шага записывается номер передвигаемого на данном шаге
элемента. 

In [5]:
import numpy as np
import itertools

array = np.array([2,6,13,7,8,10,15,1,0,3,4,5,9,11,12,14])

array = array.reshape(4,4)

print(str(array) + '\n')

def sort_by_columns(array):
    lst = sorted(itertools.chain.from_iterable(array))
    return [lst[i::len(array)] for i in range(len(array))]
    

array = np.array(sort_by_columns(array))

print(str(array) + '\n')

array = np.transpose(array)

print(str(array) + '\n')

array = np.delete(array, 0)
array = np.append(array, 0)
print(array.reshape(4,4))

[[ 2  6 13  7]
 [ 8 10 15  1]
 [ 0  3  4  5]
 [ 9 11 12 14]]

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


### Вывод